---
name: Automation Tests Run
on:
  workflow_dispatch:

jobs:
  runTests:
    name: 'Run WDIO Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          ref: main
          node-version: '18.x'
    
      - name: Cache Node Modules
        id: node-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
    
      - name: NPM Install
        run: npm install
    
      - name: Compile Typescript
        run: tsc
    
      - name: Run WDIO tests
        run: npm run run-tests